### ISSUE TITLE
Add Hadoop

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#1]
Add Hadoop in `data_science/miscellaneous`

**Comment by agarwalprashasti** [comment]
hello,I would like to work on this.
What are the requirements?

**Comment by uemarica** [comment]
Hey i would like to work on this.

**Comment by the-ethan-hunt** [comment]
@agarwalprashasti you need have a sufficient knowledge of Hadoop to write an article on it. :smile:

**Comment by uemarica** [comment]
Can i work on this,i have enough knowledge of hadoop?

**Comment by the-ethan-hunt** [comment]
Sure! Assigned to @uemarica

**Comment by the-ethan-hunt** [comment]
Time limit exceeded. Issue up for grabs!

**Comment by Pallavi024** [comment]
I would like to work on this @the-ethan-hunt

**Comment by the-ethan-hunt** [comment]
Assigned to @Pallavi024
