### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#102]
Add in `guides/DevOps`

**Comment by pbiswas101** [comment]
@the-ethan-hunt I would like to work on this one!

**Comment by the-ethan-hunt** [comment]
Complete your PR edit so that this can be assigned to you

**Comment by pbiswas101** [comment]
Okay. Sure.

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101
