### ISSUE TITLE
Honeypots

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#11]
Add Honeypots in `guides/Security`

**Comment by allrib** [comment]
I want to take up this :)

**Comment by Pallavi024** [comment]
I would like to work on this @the-ethan-hunt

**Comment by megha070** [comment]
I would like to work on this sir!

**Comment by the-ethan-hunt** [comment]
Assigned to @megha070 . 
@Pallavi024 please complete your edits of the pending PR and work on another issue :smile:
