### ISSUE TITLE
D3.js

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#110]
I want to work on this @the-ethan-hunt

**Comment by pbiswas101** [comment]
So, I've made the changes as per requested for PR #109 
Can I work on this one now?

**Comment by pbiswas101** [comment]
Also in which folder should I put this file?

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101 
Put in data visualisation folder

**Comment by the-ethan-hunt** [comment]
Time window exceeded! Issue up for grabs!

**Comment by pbiswas101** [comment]
But you said not to make a PR on this weekend!! @the-ethan-hunt

**Comment by pbiswas101** [comment]
I've already written about it.
