### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#114]
Include in `guides/databases`

**Comment by Shristy2404** [comment]
I'll work on this and include `SQLAlchemy` in the same folder as well? Both are used together mostly, in Postgres based database structure.

**Comment by mohit2016** [comment]
I want to take this issue. Please assign :-)

**Comment by the-ethan-hunt** [comment]
Assigned to @Shristy2404

**Comment by CoderJolly** [comment]
what is the issue, it nt clear from description

P.S. I m a beginner

**Comment by CoderJolly** [comment]
Is it unassigned ? If nt den pls assign it to me....
