### ISSUE TITLE
Grails

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#116]
Write in `guide/web_frameworks`

**Comment by mohit2016** [comment]
I will work on this. I will write
what is groovy on grails, Introduction
Grails Installation, 
running your first app
about grails controller, model and views
Is there any particular requirement or topic you wanted me to write about @the-ethan-hunt ?

**Comment by the-ethan-hunt** [comment]
Assigned to @mohit2016 . 
The abovementioned topics are enough

**Comment by the-ethan-hunt** [comment]
Time limit exceeded! Issue up for grabs!

**Comment by mohit2016** [comment]
@the-ethan-hunt i had written the article, it's just i couldn't upload it. I've now sent PR for the same. will you consider it to be my issue or want to reassign?
