### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#122]
@the-ethan-hunt I would like to work on this!

**Comment by the-ethan-hunt** [comment]
Why just Tensorflow.js?
I suggest you to write on TensorFlow including a passage on tensorflow.js

**Comment by pbiswas101** [comment]
Alright! Sure!

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101 
Include in `guides/data_science/machine_learning`

**Comment by pbiswas101** [comment]
Okay!

**Comment by the-ethan-hunt** [comment]
@pbiswas101 new edit:
Include this in ~`guides/data_science/machine_learning`~ `guides/data_science/deep_learning`

**Comment by pbiswas101** [comment]
Okay
