### ISSUE TITLE
Turing Test

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#125]
I would like to work on this @the-ethan-hunt 

`guides/logic`

**Comment by the-ethan-hunt** [comment]
Please work on your previous PR first.

**Comment by pbiswas101** [comment]
@the-ethan-hunt I've made the changes on my PR #124 
Now, please assign this one to me!

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101
