### ISSUE TITLE
Hidden Markov Model

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#126]
Include in `guides/data_science/machine_learning`
A pictorial representation included would be helpful

**Comment by Pallavi024** [comment]
I would like to work on this

**Comment by megha070** [comment]
I would like to work on this!

**Comment by the-ethan-hunt** [comment]
Assigned to @Pallavi024 
P.S. This is a topic where I would require more depth than you usually delve in , @Pallavi024  :smile:

**Comment by the-ethan-hunt** [comment]
@megha070 please complete your previous PR.
@Pallavi024 please complete the allotted Issue #113
And both of you, please work on the website issue too.

**Comment by Pallavi024** [comment]
@the-ethan-hunt  sir I have completed the issue #113 and even made a pull request for the same yesterday only

**Comment by the-ethan-hunt** [comment]
Assigned to @Pallavi024
