### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#13]
Add Django in `guides/Python`

**Comment by Logan1x** [comment]
Hey @the-ethan-hunt i would like to work on this.
Does this issue count in gssoc?

**Comment by the-ethan-hunt** [comment]
Yes, @Logan1x . It is assigned to you now.
Assigned to @Logan1x

**Comment by the-ethan-hunt** [comment]
Issue up for grabs!

**Comment by megha070** [comment]
I would like to work on this @the-ethan-hunt !

**Comment by mohit2016** [comment]
@the-ethan-hunt I want to write about it..

**Comment by the-ethan-hunt** [comment]
Assigned to @megha070
