### ISSUE TITLE
Add ssh 

### ISSUE THREAD

**Issue by thisisabdus** [the-ethan-hunt/first-timers-guide#133]
- About SSH 
- How to connect to github using SSH 
- Login to a remote PC using SSH

**Comment by the-ethan-hunt** [comment]
Assigned to @thisisabdus

**Comment by thisisabdus** [comment]
I will make PR by tomorrow.

**Comment by the-ethan-hunt** [comment]
@thisisabdus you are crossing the deadline!

**Comment by imkaka** [comment]
@the-ethan-hunt I want to work on this.

**Comment by megha070** [comment]
I would like to work on this @the-ethan-hunt !!

**Comment by sourabh1031** [comment]
@the-ethan-hunt  i can work on this

**Comment by ManishaTripathy** [comment]
I would like to work on this.
