### ISSUE TITLE
Restructured text guide

### ISSUE THREAD

**Issue by sourabh1031** [the-ethan-hunt/first-timers-guide#138]
I will be writing about it basic syntax, applications, and usage in technical documentation

**Comment by the-ethan-hunt** [comment]
@sourabh1031 my two cents on why this article is not required:
- There are already several excellent guides for beginners in reStructured text and any cheatsheets
- The topic is regarded as a documentation 'language' not a concept. We aim to explain concepts to newbies.
Try to bring up another issue :smile: 
Closing this one
