### ISSUE TITLE
flask

### ISSUE THREAD

**Issue by sourabh1031** [the-ethan-hunt/first-timers-guide#139]
@the-ethan-hunt i would like to work on it i will describe basic introduction about flask, installing configuration, use, and flask vs Django

**Comment by megha070** [comment]
I would like to work on this!!

**Comment by sourabh1031** [comment]
@megha070  actually i have opened up the issue and asked to get it assigned to me . Can  you please work on another or you can open another issue as well

**Comment by megha070** [comment]
Ohh!! I am sorry I did'nt notice.

**Comment by sourabh1031** [comment]
@megha070 np

**Comment by the-ethan-hunt** [comment]
Assigned to @sourabh1031 
To both of you @sourabh1031 and @megha070 : good coordination!
