### ISSUE TITLE
Material Design/Materialize.css

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#142]
Topics to include:
- What is Material Design?
- Design Principle
- Materialize.css (framework)

@the-ethan-hunt I would like to work on this one!
Let me know your thoughts as to which one I sould focus more **Material Design** or **Materialize.css** or both!

**Comment by the-ethan-hunt** [comment]
Material Design is better
Assigned to @pbiswas101
