### ISSUE TITLE
Writing Documentation

### ISSUE THREAD

**Issue by Man-Jain** [the-ethan-hunt/first-timers-guide#143]
I would like to write a guide on how to write documentation, why to write it and the different tools we can use like Markdown and RST. Please assign this issue to me.

**Comment by the-ethan-hunt** [comment]
@Man-Jain there are various really good tools for this. An issue was raised previously too for this but I have specified the reasons for why it is not required. See #138

**Comment by Man-Jain** [comment]
Okay, I have understood your point. No problem I will find something else to write on. :)
