### ISSUE TITLE
vanilla js

### ISSUE THREAD

**Issue by megha070** [the-ethan-hunt/first-timers-guide#149]
I will write about vanilla js ,it's installation

**Comment by the-ethan-hunt** [comment]
Assigned to @megha070

**Comment by the-ethan-hunt** [comment]
Issue up for grabs!

**Comment by pbiswas101** [comment]
I would like to work on this one!!

**Comment by the-ethan-hunt** [comment]
Please mention issue number while pulling a PR. Closing this issue
