### ISSUE TITLE
Dining philosophers problem

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#15]
Add in `guides/Logic`

**Comment by mangalnathanvg** [comment]
Hi I am going to work on this Issue.

**Comment by pbiswas101** [comment]
@the-ethan-hunt Can I work on this issue?

**Comment by the-ethan-hunt** [comment]
Sure! assigned to @pbiswas101

**Comment by the-ethan-hunt** [comment]
Update: @pbiswas101 please work on this issue before working on other issues

**Comment by pbiswas101** [comment]
@the-ethan-hunt sure!

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101
