### ISSUE TITLE
Virtual Reality/Augmented Reality

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#150]
I would like to work on this @the-ethan-hunt

**Comment by pbiswas101** [comment]
Points to be included:
- What is VR?
- What is AR?
- Differences!
- Impact on the world
- Future possibilities

**Comment by the-ethan-hunt** [comment]
@pbiswas101 the topic has been on a lot of hype and covering it again might seem trivial. How about finding another nice topic like you usually do?

**Comment by pbiswas101** [comment]
Okay! Closing this issue then!
