### ISSUE TITLE
Next.js

### ISSUE THREAD

**Issue by sourabh1031** [the-ethan-hunt/first-timers-guide#154]
@the-ethan-hunt I would like to work on it.

**Comment by the-ethan-hunt** [comment]
Assigned to @sourabh1031

**Comment by sourabh1031** [comment]
@the-ethan-hunt  i mean to say this --> https://nextjs.org/learn/

**Comment by sourabh1031** [comment]
By the way thanks @the-ethan-hunt  i came to know one more new thing from you
