### ISSUE TITLE
Prototypal Inheritance

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#161]
@the-ethan-hunt I would like to work on this!

Topics to include:
- What is Prototypal Inheritance?
- How is it different from Classical OOP?
- Which languages support it?

**Comment by pbiswas101** [comment]
Also state where should I put this?

**Comment by the-ethan-hunt** [comment]
@pbiswas101 I have a very vague knowledge of OOP.
@RN0311 can you help out here 😅

**Comment by pbiswas101** [comment]
@the-ethan-hunt @RN0311
So, shall I start writing about this one?

**Comment by the-ethan-hunt** [comment]
Yes prepare the article and once the folder data is provided , you can do the rest. 😄

**Comment by pbiswas101** [comment]
Can you label it? @the-ethan-hunt

**Comment by RN0311** [comment]
@pbiswas101 : Hey! That's a great idea of distinguishing between classical OOPS as well as describing Prototype-based-programming and giving language support of JS, Lua etc! Try to include this resource - ``` https://medium.com/@kevincennis/prototypal-inheritance-781bccc97edb ``` - a great article indeed! :wink: 
@the-ethan-hunt : We can add labels like ```web-development```,  ```GSSOC``` et all. :smile:

**Comment by pbiswas101** [comment]
@the-ethan-hunt please **label**/**assign** it & state the **folder** for the file!
I've written the file already, waiting for the response as where should I put it!?
