### ISSUE TITLE
Nuxt.js

### ISSUE THREAD

**Issue by megha070** [the-ethan-hunt/first-timers-guide#164]

**Comment by the-ethan-hunt** [comment]
Assigned to @megha070

**Comment by sourabh1031** [comment]
@megha070 If you are busy can i take up this issue

**Comment by megha070** [comment]
@sourabh1031  I am really very sorry but I raised a PR for this issue and it has been merged already!!

**Comment by sourabh1031** [comment]
@megha070 np you have done the work so now you can close the issue by yourself

**Comment by megha070** [comment]
Thanks a ton !! I was'nt knowing about this!!
