### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#17]
Add the guide in `guides/Cloud_development`

**Comment by Dhiraj240** [comment]
Hi,i would like to make an article over it.Can i ?

**Comment by Dhiraj240** [comment]
Hi,i would like to make an article over it.Can i ? also will it be counted for Gssoc?

**Comment by the-ethan-hunt** [comment]
Yes, it will count for GSSOC. 
Issue assigned to @Dhiraj240

**Comment by the-ethan-hunt** [comment]
Time limit exceeded @Dhiraj240 ! Issue unassigned and up for grabs!

**Comment by mohit2016** [comment]
I would love to write about Azure. Can you assign this issue to me. I will complete it asap.

**Comment by the-ethan-hunt** [comment]
Assigned to @mohit2016
