### ISSUE TITLE
Classification in Machine Learning

### ISSUE THREAD

**Issue by mohit2016** [the-ethan-hunt/first-timers-guide#180]
@the-ethan-hunt Please assign this issue to me. I will write about the different algorithms for classification.

**Comment by the-ethan-hunt** [comment]
@mohit2016 this will be a topsider issue. And there will be an article for every algorithm. Do you want to continue with it?

**Comment by mohit2016** [comment]
Sure. I will do it.!

**Comment by mohit2016** [comment]
Sorry, I cannot continue for a few days due to my poor health, got admitted to the hospital. 
@the-ethan-hunt   Please unassign this issue.

**Comment by the-ethan-hunt** [comment]
Issue up for grabs!

**Comment by pbiswas101** [comment]
@the-ethan-hunt I would like to work on this & just to be sure when you said "`there will be an article for every algorithm`" did you meant these eight classification algorithms, only?
- Logistic Regression
- Naive Bayes Classifier
- Support Vector Machines
- Decision Trees
- Boosted Trees
- Random Forest
- Neural Networks
- Nearest Neighbor
