### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by sourabh1031** [the-ethan-hunt/first-timers-guide#192]
@the-ethan-hunt i would like to work on this

**Comment by RN0311** [comment]
@sourabh1031 : Please go ahead! Even if GSSoC end is around the corner, but I would still like to continue reviewing PR's, provided @the-ethan-hunt approves that! :wink: 

But, right now try to write an article on this topic & I'll review your PR! :smiley: :

**Comment by the-ethan-hunt** [comment]
Assigned to @sourabh1031

**Comment by sourabh1031** [comment]
@RN0311 please review
