### ISSUE TITLE
Contributing.md is not clear 

### ISSUE THREAD

**Issue by fdmarcin** [the-ethan-hunt/first-timers-guide#201]
Hi,
I would like to improve this doc's readability. Is it okay if I fork and do a PR?

**Comment by the-ethan-hunt** [comment]
@fdmarcin would you please state how the `CONTRIBUTING.md` is not clear? :smile:

**Comment by fdmarcin** [comment]
Sorry about the issue title being too vague. I didn't know how to phrase it better.

I think the text could use some editing improvements, such as making some sentences easier to understand for non-native English speakers.
For example, I'd change:
>But, of course there are some contributing rules: Like how filling out the comment part or how to make an appropriate pull request.

to

> Of course there are some contributing rules: such as how fill out the comment part, or how to make an appropriate pull request.

How about I give it a try, and you see if you like the changes?

**Comment by the-ethan-hunt** [comment]
@fdmarcin sure! I agree some sentences can be tweaked to make it easier to understand for non-English speakers. Let's give this a shot! :tada:

**Comment by fdmarcin** [comment]
@the-ethan-hunt 
What does **do it** mean here? Create an issue? Or write an article?
>If you are writing an article about which an issue has not been defined, you are free to do it!
