### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#21]
Add articles on git. The folder should be titled as in `guides/git`. Include necessary code snippets like `git merge`, `git pull` etc. The article should be comparatively much longer than other articles due to the content

**Comment by sherribooher** [comment]
I would like to work on this, please.

**Comment by the-ethan-hunt** [comment]
@sherribooher , feel free to take up the issue! :smile:

**Comment by codezoned** [comment]
I'll also like to take up this issue

**Comment by the-ethan-hunt** [comment]
Feel free to! @codezoned !

**Comment by Tyraelium** [comment]
Hello every one, can i work on this task please ?

**Comment by the-ethan-hunt** [comment]
Closing this issue
