### ISSUE TITLE
Wireframing

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#22]
Add the article in `guides/Visual_design`

**Comment by ap1459** [comment]
Hello @the-ethan-hunt, I would like to contribute to this, as I have had some experience with high-fidelity wireframing tools such as Justinmind.

**Comment by the-ethan-hunt** [comment]
@ap1459 , you are free to work on this! If you can, please also add articles on these tools. Also before working, please see #24 . :smile:

**Comment by ap1459** [comment]
Okay great thanks @the-ethan-hunt. So should I add two separate articles? One for Wireframing in general, and then one for Justinmind?

**Comment by the-ethan-hunt** [comment]
@ap1459 , feel free to create them! Add both the articles in `guides/Visual_design/Wireframing` then.

**Comment by ap1459** [comment]
Hi @the-ethan-hunt, I have made the changes but am having difficulty pushing them. I am using GitKraken and when I attempt to push the changes, it says - 

"Access denied. Make sure that you have access to do that action on that remote and try again. If the-ethan-hunt is an organization on GitHub, you may need to request or grant access to the organization for GitKraken."

**Comment by the-ethan-hunt** [comment]
Closing this issue
