### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#27]
Add in `guides/DevOps`

**Comment by your1p** [comment]
Hi, 

I want to explain what is Vagrant. I use it everyday. 

Thanks.

**Comment by the-ethan-hunt** [comment]
Sorry for the late reply!
assigned to @your1p

**Comment by megha070** [comment]
I would like to work on this  issue @the-ethan-hunt !

**Comment by sourabh1031** [comment]
@the-ethan-hunt i want to work on this issue.

**Comment by the-ethan-hunt** [comment]
@sourabh1031 please complete your previous PR before claiming the issue,

**Comment by Pallavi024** [comment]
@the-ethan-hunt  I would like to work on this issue

**Comment by sourabh1031** [comment]
@Pallavi024 if you don't mind i already referenced it

**Comment by Pallavi024** [comment]
Its okay, you can take this issue @sourabh1031 . I'll take another issue :smiley:

**Comment by the-ethan-hunt** [comment]
Assigned to @sourabh1031
