### ISSUE TITLE
Monty Hall problem

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#33]
Add in `guides/logic`

**Comment by pmanjunath29** [comment]
Hi - I'd like to take this issue. It's my first contribution. Thanks.

**Comment by the-ethan-hunt** [comment]
Assigned to @pmanjunath29

**Comment by pmanjunath29** [comment]
Thank you - I have raised a pull request. Please let me know if you have any feedback.

**Comment by the-ethan-hunt** [comment]
Closing this after a great PR by @pmanjunath29

**Comment by pmanjunath29** [comment]
Thank you, I appreciate your help, this is my first ever commit to Git.
