### ISSUE TITLE
CakePHP3

### ISSUE THREAD

**Issue by Haradwaith** [the-ethan-hunt/first-timers-guide#36]
Add a guide about CakePhp 3

**Comment by the-ethan-hunt** [comment]
Include the article in `guides/Web-frameworks`

**Comment by mohit2016** [comment]
I want to take this issue... @the-ethan-hunt please assign

**Comment by the-ethan-hunt** [comment]
Assigned to @mohit2016 
P.S. Please don't try to take up multiple issues.

**Comment by mohit2016** [comment]
I couldn't complete yet. I need more 3-4 hours. I've started working and I will submit it tonight positively.

**Comment by mohit2016** [comment]
Completed PR sent.
