### ISSUE TITLE
Add Text classification

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#4]
Add the article to [this folder](https://github.com/the-ethan-hunt/first-timers-guide/tree/master/guides/data_science/natural_language_processing)

**Comment by the-ethan-hunt** [comment]
Assigned to @dhairyabaweja

**Comment by the-ethan-hunt** [comment]
Time limit exceeded @dhairyabaweja ! 
Issue up for grabs!

**Comment by pbiswas101** [comment]
@the-ethan-hunt I would like to work on this!

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101
