### ISSUE TITLE
Add Ansible

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#5]
Add to `guides/DevOps`

**Comment by newtorob** [comment]
I would like to take on this issue, if possible?

**Comment by the-ethan-hunt** [comment]
Feel free to @newtorob !

**Comment by Pallavi024** [comment]
I would like to work on this

**Comment by the-ethan-hunt** [comment]
Sure! Assigned to @Pallavi024
