### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#51]
Explain each type of regression with clear and concise information. No mathematical jargon would be allowed.
Add in `guides/data_science/machine_learning`

**Comment by imkaka** [comment]
I want to take this @the-ethan-hunt .

**Comment by the-ethan-hunt** [comment]
Assined to @imkaka

**Comment by the-ethan-hunt** [comment]
Time limit exceeded! Issue up for grabs!

**Comment by imkaka** [comment]
I am working on it I will complete by some hours @the-ethan-hunt

**Comment by mohit2016** [comment]
I want to take this issue @the-ethan-hunt :)
