### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#6]
Add to `guides/DevOps`

**Comment by Shristy2404** [comment]
I'd like to work on this, please?

**Comment by the-ethan-hunt** [comment]
Assigned to @Shristy2404

**Comment by Shristy2404** [comment]
There's no DevOps folder in guides. Does it need to be created?

**Comment by the-ethan-hunt** [comment]
Yes @Shristy2404 
P.S. Today is the deadline for you.

**Comment by Shristy2404** [comment]
I opened a pull request. Let me know if any corrections are required.  :)
