### ISSUE TITLE
Add NodeJS

### ISSUE THREAD

**Issue by thisisabdus** [the-ethan-hunt/first-timers-guide#63]
Add a starter guide on Node JS.

**Comment by thisisabdus** [comment]
I would love to contribute on this issue if added.

**Comment by the-ethan-hunt** [comment]
Please explain what would you be writing in this topic.

**Comment by the-ethan-hunt** [comment]
This would certainly a nice article. Please begin writing in the Markdown format.

**Comment by thisisabdus** [comment]
Sure. Should I make a PR when I am done with this?

**Comment by the-ethan-hunt** [comment]
Yes @thisisabdus . Please mention the issue number too

**Comment by the-ethan-hunt** [comment]
Issue up for grabs!

**Comment by thisisabdus** [comment]
Re-claiming it. I got busy with Uni exams.

**Comment by mohit2016** [comment]
I can write about NodeJS, if you assign this issue to me like basic setup, how to start with NPM , v8 JS , EXpress framework.
 I will complete it very soon..!!

**Comment by thisisabdus** [comment]
@the-ethan-hunt , should I make a PR? Waiting for your approval

**Comment by the-ethan-hunt** [comment]
Assigned to @thisisabdus . Please complete it in the time window :smile:

**Comment by thisisabdus** [comment]
I will make PR today for sure. Thank you
