### ISSUE TITLE
Add website?

### ISSUE THREAD

**Issue by ScottBrenner** [the-ethan-hunt/first-timers-guide#64]
Creating a static website for this repository should be pretty straight forward, anyone up to the task? See https://pages.github.com/

**Comment by pbiswas101** [comment]
Yes, I would love to work on this! @ScottBrenner 
Can I work on this? @the-ethan-hunt

**Comment by the-ethan-hunt** [comment]
Great idea! Perhaps the site could look much like this [one](http://search.opengenus.org/)?

**Comment by sourabh1031** [comment]
Hello @the-ethan-hunt I am participant of GSSOC. I would be happy to contribute to it if you want

**Comment by Dhiraj240** [comment]
I would also like to work with you guys @ScottBrenner @pbiswas101 can i work with them? @the-ethan-hunt

**Comment by the-ethan-hunt** [comment]
@Dhiraj240 , you already have been assigned an issue. 
Issue assigned to @ScottBrenner **only** for now

**Comment by thisisabdus** [comment]
Hey Scott, gonna build it using static site generator? Like Hugo or Jekyll?

**Comment by ScottBrenner** [comment]
Yes - also, someone else is welcome to work on this instead of me.

**Comment by pbiswas101** [comment]
Then I would like to work on it!

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101

**Comment by the-ethan-hunt** [comment]
Issue unassigned and up for grabs!

**Comment by shreyateeza** [comment]
@the-ethan-hunt I want to work on this issue!

**Comment by the-ethan-hunt** [comment]
Assined to @Dhiraj240

**Comment by the-ethan-hunt** [comment]
Assigned to @shreyateeza

**Comment by Dhiraj240** [comment]
@shreyateeza @the-ethan-hunt  can we work together? If you don't mind @shreyateeza

**Comment by shreyateeza** [comment]
@Dhiraj240 Just saw your comment. A PR regarding this has been created(#101).
Feel free to take another issue!

**Comment by Dhiraj240** [comment]
okay, cool.

**Comment by Pallavi024** [comment]
@the-ethan-hunt  I would like to work on this.Can I work on this ?

**Comment by megha070** [comment]
I would like to work on this as well!
If you don't mind @Pallavi024 . Can we both work on this!

**Comment by shreyateeza** [comment]
@Pallavi024 @megha070 I am working on this and will soon update my PR(#101).

**Comment by the-ethan-hunt** [comment]
@Pallavi024 and @megha070 why don't you two work on this together while @shreyateeza works on her site.

**Comment by jinojossy93** [comment]
Hi @the-ethan-hunt ,

Can I take this up?

**Comment by Qamar30** [comment]
I'm interested how far is the website

**Comment by the-ethan-hunt** [comment]
@Qamar30 there has been no progress. You are free to take up the issue.

**Comment by EdgeKing810** [comment]
Hello @the-ethan-hunt!
Must be bored of getting people to comment on this...

Anyway I want to take it. I participated in GCI this year and have kind of good knowledge in making websites using github pages and jekyll/HTML & CSS...

I need some more details tho... What should the website look like? I mean does the first page needs to only correspond to the ``README.md``?

Also, I'm thinking of working on [this issue](https://github.com/the-ethan-hunt/first-timers-guide/issues/216).

**Comment by EdgeKing810** [comment]
I created an ``index.rst`` as the first page of the website after the ``README.md`` file. Let me know if it's good.
