### ISSUE TITLE
[Logic] The Hardest Logic Puzzle Ever

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#65]
This would be an article on _The Three Gods Riddle_!
Seems to me a perfect fit for the *logic* section.

**Comment by pbiswas101** [comment]
@the-ethan-hunt  if you think this issue would be appropriate then please add a label to this Issue regarding GSSOC.

**Comment by the-ethan-hunt** [comment]
Closing this issue
