### ISSUE TITLE
Add SVN 

### ISSUE THREAD

**Issue by thisisabdus** [the-ethan-hunt/first-timers-guide#78]
I want to write an article on SVN. Few points I would like to cover are,

- What's SVN
- How to install it in windows and Linux 
- How to use it for managing project 
... and more!

Let me know your thoughts.

**Comment by mohit2016** [comment]
I want to take this issue :)

**Comment by the-ethan-hunt** [comment]
Go for it. Assigned to @thisisabdus

**Comment by thisisabdus** [comment]
Thank you. :heart:
