### ISSUE TITLE
Color Theory

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/first-timers-guide#8]
Add Color Theory in `guides/Visual_design`

**Comment by seowwj** [comment]
Did you mean you're looking for someone to help contribute to color theory?

If so I may be able to help 😄

**Comment by the-ethan-hunt** [comment]
Yes! You can write a guide article on it! You can also write on other
issues too! If you have any more doubts you are free to ask! :)

On Jan 12, 2018 8:39 AM, "seowwj" <notifications@github.com> wrote:

Did you mean you're looking for someone to help contribute to color theory?

If so I may be able to help 😄

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/the-ethan-hunt/first-timers-guide/issues/8#issuecomment-357130968>,
or mute the thread

**Comment by Pallavi024** [comment]
I would like to work on this @the-ethan-hunt , how should i get myself assigned?? and is this a part of gssoc?

**Comment by the-ethan-hunt** [comment]
Yes this is a part of GSSOC.
Assigned to @Pallavi024
