### ISSUE TITLE
Web Assembly

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#86]
@the-ethan-hunt I would like to write about this based on the following topics!

- What is it?
- What does it bring to the table?
- Does it mean the death of JavaScript?
- Supporting Languages
- What does it mean for the future?

I think this should go to **guides/web_development** folder.. so please label & assign it so that I can start writing about it!

**Comment by the-ethan-hunt** [comment]
The first two points are alright. I don't feel the need to include "what does it mean for the future"(your call to include this) and "does it mean the death of javascript?"( no opinions will be entertained)
Assigning this issue to @pbiswas101

**Comment by pbiswas101** [comment]
Thanks @the-ethan-hunt
Sure won't be including those!
