### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by saberprashant** [the-ethan-hunt/first-timers-guide#93]
Hey, I would like to write a small guide related to Angular(mainly Angular 5) framework. I will provide some basic details about it, and will also explain "How a beginner can setup their first project" with some basic syntax.

**Comment by saberprashant** [comment]
@the-ethan-hunt can you please assign me this issue under GSSOC?

**Comment by the-ethan-hunt** [comment]
Alright. However, a proper demo should be given.
Assigned to @saberprashant

**Comment by saberprashant** [comment]
Ya sure, I will try to make it simple and informative and will try to push it up in 3-4 days. 👍

**Comment by the-ethan-hunt** [comment]
Time limit exceeded! Issue up for grabs!

**Comment by megha070** [comment]
I would like to work on this @the-ethan-hunt !!

**Comment by the-ethan-hunt** [comment]
Please complete work on your previous PR

**Comment by mohit2016** [comment]
I want to take this issue. @the-ethan-hunt Please assign to me. Thank you :-)

**Comment by saberprashant** [comment]
I am working on this already @the-ethan-hunt

**Comment by the-ethan-hunt** [comment]
Assigned to @mohit2016 
@saberprashant you have exceeded the time limit as under GSSOC rules
@megha070 please don't request to get assigned on every issue

**Comment by megha070** [comment]
@the-ethan-hunt sorry for the inconvenience !!
